src/client/SurveyMe.WebApplication/Models/ViewModels/Answers/AnswerViewModel.cs
namespace SurveyMe.WebApplication.Models.ViewModels.Answers
{
    public sealed class AnswerViewModel
    {
        public Guid SurveyId { get; set; }
        
        public ICollection<BaseAnswerViewModel> QuestionsAnswers { get; set; }
    }
}

src/client/SurveyMe.WebApplication/Models/ViewModels/Answers/BaseAnswerViewModel.cs
using SurveyMe.DomainModels.Common;

namespace SurveyMe.WebApplication.Models.ViewModels.Answers;

public abstract class BaseAnswerViewModel
{
    public QuestionType QuestionType { get; set; }
    
    public Guid QuestionId { get; set; }
}

src/client/SurveyMe.WebApplication/Models/ViewModels/Answers/CheckboxAnswerViewModel.cs
namespace SurveyMe.WebApplication.Models.ViewModels.Answers;

public sealed class CheckboxAnswerViewModel : BaseAnswerViewModel
{
    public IEnumerable<Guid>? OptionIds { get; set; }
}

src/client/SurveyMe.WebApplication/Models/ViewModels/Answers/FileAnswerViewModel.cs
using SurveyMe.WebApplication.Models.ViewModels.Files;

namespace SurveyMe.WebApplication.Models.ViewModels.Answers
{
    public class FileAnswerViewModel : BaseAnswerViewModel
    {
        public FileInfoViewModel File { get; set; }

        public Guid FileInfoId { get; set; }
    }
}

src/client/SurveyMe.WebApplication/Models/ViewModels/Answers/RadioAnswerViewModel.cs
namespace SurveyMe.WebApplication.Models.ViewModels.Answers;

public sealed class RadioAnswerViewModel : BaseAnswerViewModel
{
    public Guid OptionId { get; set; }
}

src/client/SurveyMe.WebApplication/Models/ViewModels/Answers/RateAnswerViewModel.cs
namespace SurveyMe.WebApplication.Models.ViewModels.Answers;

public sealed class RateAnswerViewModel : BaseAnswerViewModel
{
    public double RateAnswer { get; set; }
}

src/client/SurveyMe.WebApplication/Models/ViewModels/Answers/ScaleAnswerViewModel.cs
namespace SurveyMe.WebApplication.Models.ViewModels.Answers;

public sealed class ScaleAnswerViewModel : BaseAnswerViewModel
{
    public double ScaleAnswer { get; set; }
}

src/client/SurveyMe.WebApplication/Models/ViewModels/Answers/TextAnswerViewModel.cs
namespace SurveyMe.WebApplication.Models.ViewModels.Answers;

public sealed class TextAnswerViewModel : BaseAnswerViewModel
{
    public string? TextAnswer { get; set; }
}

src/client/SurveyMe.WebApplication/Models/ViewModels/Surveys/SurveyAddOrEditViewModel.cs
using System.ComponentModel.DataAnnotations;
using SurveyMe.WebApplication.Models.ViewModels.Questions;

namespace SurveyMe.WebApplication.Models.ViewModels.Surveys
{
    public sealed class SurveyAddOrEditViewModel
    {
        public Guid Id { get; set; }
        
        [Required]
        public string Name { get; set; }
        
        [Required]
        public ICollection<QuestionAddOrEditViewModel> Questions { get; set; }
    }
}

src/client/SurveyMe.WebApplication/Models/ViewModels/Surveys/SurveyDeleteViewModel.cs
namespace SurveyMe.WebApplication.Models.ViewModels.Surveys
{
    public class SurveyDeleteViewModel
    {
        public Guid Id { get; set; }

        public string Name { get; set; }
    }
}

src/client/SurveyMe.WebApplication/Models/ViewModels/Surveys/SurveyViewModel.cs
using SurveyMe.WebApplication.Models.ViewModels.Questions;

namespace SurveyMe.WebApplication.Models.ViewModels.Surveys
{
    public sealed class SurveyViewModel
    {
        public Guid Id { get; set; }

        public string Name { get; set; }
        
        public ICollection<QuestionViewModel> Questions { get; set; }

    }
}

src/client/SurveyMe.WebApplication/Models/ViewModels/Surveys/SurveyWithLinksViewModel.cs
namespace SurveyMe.WebApplication.Models.ViewModels.Surveys
{
    public sealed class SurveyWithLinksViewModel
    {
        public Guid Id { get; set; }

        public string Name { get; set; }

        public DateTime LastChangeDate { get; set; }

        public string? SurveyLink { get; set; }

        public string? ResultLink { get; set; }
    }
}

src/client/SurveyMe.WebApplication/Controllers/FilesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.StaticFiles;
using Refit;
using SurveyMe.Services.Abstracts;
using SurveyMe.Services.Exceptions;

namespace SurveyMe.WebApplication.Controllers;

[Microsoft.AspNetCore.Authorization.Authorize]
public class FilesController : Controller
{
    private readonly IFileService _fileService;
    private readonly FileExtensionContentTypeProvider _fileExtensionContentTypeProvider;
    
    
    public FilesController(IFileService fileService, FileExtensionContentTypeProvider fileExtensionContentTypeProvider)
    {
        _fileService = fileService;
        _fileExtensionContentTypeProvider = fileExtensionContentTypeProvider;
    }
    
    
    [HttpPost]
    public async Task<IActionResult> Upload([FromForm]IFormFile fileModel)
    {
        if (fileModel == null)
        {
            throw new BadRequestException("File upload error");
        }
        
        var fileStream = fileModel.OpenReadStream();

        var getContentResult = _fileExtensionContentTypeProvider
            .TryGetContentType(fileModel.FileName, out var mime);

        if (!getContentResult)
        {
            throw new BadRequestException("No such file type");
        }

        var file = new StreamPart(fileStream, fileModel.FileName, mime);
        
        var fileInfo = await _fileService.UploadAsync(file);
        
        return Ok(fileInfo);
    }
}

src/client/SurveyMe.WebApplication/Controllers/SurveysController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using SurveyMe.DomainModels.Request.Answers;
using SurveyMe.DomainModels.Request.Queries;
using SurveyMe.DomainModels.Request.Surveys;
using SurveyMe.Services.Abstracts;
using SurveyMe.Services.Exceptions;
using SurveyMe.WebApplication.Converters;
using SurveyMe.WebApplication.Models.ViewModels.Answers;
using SurveyMe.WebApplication.Models.ViewModels.Pages;
using SurveyMe.WebApplication.Models.ViewModels.Statistics;
using SurveyMe.WebApplication.Models.ViewModels.Surveys;
using System.Text.Json;

namespace SurveyMe.WebApplication.Controllers;

[Microsoft.AspNetCore.Authorization.Authorize]
public class SurveysController : Controller
{
    private readonly ISurveyService _surveyService;
    private readonly IMapper _mapper;
    
    public SurveysController(ISurveyService surveyService, IMapper mapper)
    {
        _surveyService = surveyService;
        _mapper = mapper;
    }


    public async Task<IActionResult> Index(GetPageRequest request, int page = 1)
    {
        var pageResponse = await _surveyService.GetSurveysAsync(request, page);

        if (pageResponse == null)
        {
            throw new NotFoundException("Page do not exists");
        }
        
        var pageResultViewModel = _mapper.Map<PageResponseViewModel<SurveyWithLinksViewModel>>(pageResponse);
        
        foreach (var surveyWithLinksResponseModel in pageResultViewModel.Page.Items)
        {
            surveyWithLinksResponseModel.SurveyLink = 
                Url.Action(nameof(Answer), "Surveys", 
                    new { id = surveyWithLinksResponseModel.Id});
            surveyWithLinksResponseModel.ResultLink = 
                Url.Action(nameof(SurveyStatistics), "Surveys",
                    new { id = surveyWithLinksResponseModel.Id});;
        }
        
        return View(pageResultViewModel);
    }
    
    [HttpGet]
    public IActionResult AddSurvey()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> AddSurvey([FromBody] SurveyAddOrEditViewModel surveyModel)
    {
        if (surveyModel == null)
        {
            return BadRequest("Survey add error");
        }

        if (!ModelState.IsValid)
        {
            return BadRequest("Survey add error");
        }
        
        var surveyRequest = _mapper.Map<SurveyRequestModel>(surveyModel);
        await _surveyService.AddSurveyAsync(surveyRequest);

        return Ok();
    }

    [HttpGet("[action]/{id:guid}")]
    public async Task<IActionResult> EditSurvey(Guid id)
    {
        var survey =  await _surveyService.GetSurveyAsync(id);
        
        if (survey == null)
        {
            throw new NotFoundException("Survey do not exists");
        }
        
        var surveyView = _mapper.Map<SurveyAddOrEditViewModel>(survey);
        
        return View(surveyView);
    }
    
    [HttpPost]
    public async Task<IActionResult> EditSurvey([FromBody] SurveyAddOrEditViewModel surveyModel)
    {
        if (surveyModel == null)
        {
            return BadRequest("Survey edit error");
        }
        
        var surveyRequest = _mapper.Map<SurveyRequestModel>(surveyModel);
        await _surveyService.EditSurveyAsync(surveyRequest, surveyRequest.Id);
        
        return Ok();
    }
    
    [HttpGet]
    public IActionResult DeleteSurvey(SurveyDeleteViewModel surveyModel)
    {
        if (surveyModel == null)
        {
            throw new BadRequestException("Survey delete error");
        }
        
        return View(surveyModel);
    }

    [HttpPost]
    public async Task<IActionResult> DeleteConfirm(SurveyDeleteViewModel surveyModel)
    {
        if (surveyModel == null)
        {
            return BadRequest("Survey delete error");
        }
        
        await _surveyService.DeleteSurveyAsync(surveyModel.Id);

        return RedirectToAction(nameof(Index));
    }
    
    [HttpGet("[action]/{id:guid}")]
    public async Task<IActionResult> Answer(Guid id)
    {
        var survey = await _surveyService.GetSurveyAsync(id);
        
        if (survey == null)
        {
            throw new NotFoundException("Survey do not exists");
        }
        
        var surveyView = _mapper.Map<SurveyViewModel>(survey);
            
        return View(surveyView);
    }
    
    [HttpPost]
    public async Task<IActionResult> Answer([FromBody]AnswerViewModel answerViewModel)
    {
        if (answerViewModel == null)
        {
            return BadRequest("Answering error");
        }

        var answer = _mapper.Map<SurveyAnswerRequestModel>(answerViewModel);

        var options = new JsonSerializerOptions() { 
             Converters = { new AnswerRequestJsonConverter() }
        };

        var json = JsonSerializer.Serialize(answer, options);

        await _surveyService.AnswerAsync(answer, answer.SurveyId);
        
        return Ok();
    }
    
    [HttpGet]
    public async Task<IActionResult> SurveyStatistics(Guid id)
    {
        var statistic = await _surveyService.GetSurveyStatisticAsync(id);
        
        if (statistic == null)
        {
            throw new NotFoundException("Statistics for survey do not exists");
        }
        
        var statisticView = _mapper.Map<SurveyAnswersStatisticViewModel>(statistic);
        
        return View(statisticView);
    }
}

src/client/SurveyMe.WebApplication/Views/Surveys/AddSurvey.cshtml
<div id="survey-page" class="mt-4">
    <div class="errors" asp-validation-summary="All"></div>
    <div id="title-card" class="d-flex justify-center flex-column p-5">
       <p class="fs-2 text-center">Survey title</p>
       <div class="text-center">
          <input class="w-50 mt-3 survey-field input_form" id="survey-name" type="text" placeholder="Title">
       </div>
    </div>
    <div id="questions-container">
    </div>
    <div class="d-flex text-center">
      <input type="button" class="action-button survey-control survey-field m-3" id="add-question" value="Add Question"/>
      <button id="submit-survey" class="action-button survey-control survey-field m-3 btn-primary" type="button">Submit</button>
    </div>
</div>

@section Scripts
{
    <script src="~/js/AddOrEditSurvey.js"></script>
    <script>
        $(`#submit-survey`).on(`click`,
            async () => {
                const survey = {
                    name: $(`#survey-name`).val(),
                    questions: $(`.question-card`).map(function () {
                        return {
                            title: $(this).find(`.question-title`).val(),
                            options: $(this).find(`.answer-option`).map(function (){
                                return $(this).val();
                            }).get(),
                            type:questionType[$(this).find(`.type`).val()]
                        }
                    }).get()
                };
                
                $.ajax({
                    type: "POST",
                    url: `@Url.Action("AddSurvey")`,
                    contentType: 'application/json;charset=UTF-8',
                    accept: 'application/json; charset=utf-8',
                    data: JSON.stringify(survey),
                    success: function () {
                        window.location = `@Url.Action("Index", "Surveys")`;
                    },
                    failure: function (response) {
                        alert(response.responseText);
                    },
                    error: function (response) {
                        alert(response.responseText);
                   }
                });
            }
        );
 </script>   
}

src/client/SurveyMe.WebApplication/Views/Surveys/Answer.cshtml
@using SurveyMe.DomainModels.Common
@model SurveyMe.WebApplication.Models.ViewModels.Surveys.SurveyViewModel

<div id="survey-page">
    <div id="title-card" class="d-flex justify-center flex-column p-5">
       <p class="fs-2 text-center">@Model.Name</p>
    </div>
    @foreach (var question in Model.Questions)
    {
        <div class="question-card d-flex flex-column a p-5 mt-4" id="@question.Id">
            <div class="text-center">
                <p class="fs-4">@question.Title</p>
            </div>
            
                @switch (question.Type)
                {
                    case QuestionType.Text:
                        <div class="answer-field mt-3 text-center">
                            <input class="answer-data w-75" name="@question.Id" type="text">
                            <input type="hidden" class="question-type" value="text">
                        </div>
                        break;
                    case QuestionType.Radio:
                        foreach (var questionOption in question.Options)
                        {
                            <div class="answer-field">
                                <input class="answer-data" value="@questionOption.Text" name="@question.Id"
                                       id="@questionOption.Id" type="radio">
                                <label for="@questionOption.Id">@questionOption.Text</label>
                                <input type="hidden" class="question-type" value="radio">
                            </div>
                        }
                        break;
                    case QuestionType.Checkbox:
                        foreach (var questionOption in question.Options)
                        {
                            <div class="answer-field">
                                <input class="answer-data" value="@questionOption.Text" name="@question.Id" 
                                    id="@questionOption.Id" type="checkbox">
                                <label for="@questionOption.Id">@questionOption.Text</label>
                                <input type="hidden" class="question-type" value="checkbox">
                            </div>
                        }
                        break;
                    case QuestionType.File:
                        <div class="answer-field">
                            <input class="answer-data" name="@question.Id" id="files" type="file">
                            <input type="hidden" class="question-type" value="file">
                        </div>
                        break;
                    case QuestionType.Rate:
                        <div class="answer-field">
                            <fieldset class="starability-basic">
                                <input type="radio" id="@question.Id no-rate" class="input-no-rate" name="@question.Id" value="0" checked aria-label="No rating."/>
                                <input type="radio" id="@question.Id star-20" name="@question.Id" value="20"/>
                                <label for="@question.Id star-20" title="Terrible">1 star</label>
                                <input type="radio" id="@question.Id star-40" name="@question.Id" value="40"/>
                                <label for="@question.Id star-40" title="Not good">2 stars</label>
                                <input type="radio" id="@question.Id star-60" name="@question.Id" value="60"/>
                                <label for="@question.Id star-60" title="Average">3 stars</label>
                                <input type="radio" id="@question.Id star-80" name="@question.Id" value="80"/>
                                <label for="@question.Id star-80" title="Very good">4 stars</label>
                                <input type="radio" id="@question.Id star-100" name="@question.Id" value="100"/>
                                <label for="@question.Id star-100" title="Amazing">5 stars</label>
                            </fieldset>
                            <input type="hidden" class="question-type" value="rate">
                        </div>
                        break;
                    case QuestionType.Scale:
                        <div class="answer-field">
                            <label for="@question.Id">0</label>
                            <input class="answer-data" min="0" max="100" name="@question.Id" id="@question.Id" type="range">
                            <label for="@question.Id">100</label>
                            <input type="hidden" class="question-type" value="scale">
                        </div>
                        break;
                    default:
                        throw new ArgumentOutOfRangeException(nameof(question.Type), "No question type");
                }
            </div>
    
    }
    
    <button id="submit">Send answer</button>
</div>

@section Scripts
{
    <script>
    let filesInfo = new Map();
    
    $('input:file').change(
        async (e) => {
            const file = new FormData();
            file.append('fileModel', $(e.target).prop('files')[0])
            
            $.ajax({
                type: "POST",
                url: `@Url.ActionLink("Upload", "Files")`,
                contentType: false,
                processData: false,
                data: file,
                success: function (response) {
                    const data = response;
                    filesInfo.set(data.fileId, data);
                    $(e.target).parent().append(`<input class="file-id" type="hidden" id="${data.fileId}">`)
                },
                failure: function (response) {
                    alert(response.responseText);
                },
                error: function (response) {
                    alert(response.responseText);
               }
            });
        });
    
        $(`#submit`).on(`click`,
            async () => {
                const answer = {
                    surveyId: '@Model.Id',
                    questionsAnswers : $('.question-card').map(function (){
                        const type = $(this).find('.question-type').val();   
                        const questionCard = this;
                        let value;
                        let questionAnswer;
                        switch (type)
                        {
                            case 'checkbox':
                                questionAnswer = {
                                    questionType: type,
                                    questionId: $(this).attr('id'),
                                    optionIds: []
                                };
                                $(this).find('.answer-data').each(function (){  
                                    value = $(this).filter(':checked').val();
                                    const id =  $(this).filter(':checked').attr('id');
                                    if (value != null){
                                         questionAnswer.optionIds.push(id);
                                    }
                                });
                                if (questionAnswer.optionIds.length === 0)
                                    return;
                                break;
                            case 'radio':
                                questionAnswer = {
                                    questionType: type,
                                    questionId: $(this).attr('id'),
                                    optionId: ""
                                };
                                $(this).find('.answer-data').each(function (){  
                                    value = $(this).filter(':checked').val();
                                    const id =  $(this).filter(':checked').attr('id');
                                    if (value != null){
                                        questionAnswer.optionId = id;
                                    }
                                });
                                if (questionAnswer.optionId === "")
                                    return;
                                break;
                            case 'text':
                                questionAnswer = {
                                    questionType: type,
                                    questionId: $(this).attr('id'),
                                    textAnswer:  $(this).find('.answer-data').val()
                                };
                                break;
                            case 'file':
                                const id = $(questionCard).find('.file-id').attr('id');
                                const file = filesInfo.get(id);
                                
                                if (file === undefined)
                                    return;
                                
                                questionAnswer = {
                                    questionType: type,
                                    questionId: $(this).attr('id'),
                                    file: {
                                        fileId: id,
                                        contentType: file.contentType,
                                        name: file.name,
                                    },
                                    fileInfoId: id
                                };
                                break;
                            case 'rate':
                                questionAnswer = {
                                    questionType: type,
                                    questionId: $(this).attr('id'),
                                    rateAnswer: 0.0
                                };
                                
                                $(this).find('input[type=radio]').each(function (){  
                                    value = $(this).filter(':checked').val();
                                    if (value != null){
                                        questionAnswer.rateAnswer = value * 0.01;
                                    }
                                });
                                break;
                            case 'scale':
                                questionAnswer = {
                                    questionType: type,  
                                    questionId: $(this).attr('id'),
                                    scaleAnswer: 0.0
                                };
                                
                                value =  $(this).find('input[type=range]').val();
                                questionAnswer.scaleAnswer = value * 0.01;
                                break;
                        }
                                                
                        return questionAnswer;
                    }).get()
                }

                $.ajax({
                    type: "POST",
                    accept : "application/json",
                    contentType: "application/json",
                    url: `@Url.ActionLink("Answer", "Surveys", new {id = string.Empty})`,
                    data: JSON.stringify(answer),
                    success: function (response) {
                        document.location = '@Url.Action("Index")';
                    },
                    failure: function (response) {
                        alert(response.responseText);
                    },
                    error: function (response) {
                        alert(response.responseText);
                   }
                });
            }
        );
    </script>
}

src/client/SurveyMe.WebApplication/Views/Surveys/DeleteSurvey.cshtml
@model SurveyMe.WebApplication.Models.ViewModels.Surveys.SurveyDeleteViewModel
 
<p class="title">Delete @Model.Name?</p>

<form method="post" asp-controller="Surveys"
      asp-action="DeleteConfirm" asp-route-id="@Model.Id" asp-route-name="@Model.Name" class="attention-form">
    <input type="submit" class="submit-button" value="Delete" />
    <input type="button" class="discard-button" onclick="location.href = '@Url.Action("Index")'" value="Cancel" />
</form>

<div class="errors" asp-validation-summary="All"></div>

src/client/SurveyMe.WebApplication/Views/Surveys/EditSurvey.cshtml
@using SurveyMe.DomainModels.Common
@model SurveyMe.WebApplication.Models.ViewModels.Surveys.SurveyAddOrEditViewModel

<div id="survey-page" class="mt-4">
    <div class="errors" asp-validation-summary="All"></div>
    <div id="title-card" class="d-flex justify-center flex-column p-5">
        <p class="fs-2 text-center">Survey title</p>
        <div class="text-center">
            <input class="w-50 mt-3 survey-field input_form" value="@Model.Name" id="survey-name" type="text" placeholder="Title">
        </div>
    </div>
    
    <div id="questions-container">
        <script>
            const survey = JSON.parse('@Json.Serialize(Model)');
            debugger;
            const type = ['text', 'radio', 'checkbox'];
            survey.questions.forEach(question =>{
                $(`#questions-container`).append(`
                    <div class="question-card d-flex flex-column a p-5 mt-4">
                        <div class="text-center">
                            <input class="w-50 mt-3 survey-field question-title input_form" value="${question.title}" id="survey-name"
                                type="text" placeholder="Title">
                        </div>
                        <div class="question-body mt-3"></div>
                        <div id="controll" class="mt-3">
                            <input type="button" class="delete-question survey-field w-25" value="Delete question">
                        </div>
                    </div>
                `);
                
                let layout;
                                
                switch (question.type) {
                    case '@QuestionType.Radio':
                        layout = GenerateOptions(question.options, question.type);
                        break;
                    case '@QuestionType.Checkbox':
                        layout = GenerateOptions(question.options, question.type)
                        break;
                    case '@QuestionType.Text':
                        layout = `
                            <input type="hidden" class="type" value="text">
                            `;
                        break;
                    case '@QuestionType.File':
                        layout = `
                                <input type="hidden" class="type" value="file"> `;
                        break;
                    case '@QuestionType.Rate':
                        layout = `
                                <input type="hidden" class="type" value="rate"> `;
                        break;
                    case '@QuestionType.Scale':
                        layout = `
                                <input type="hidden" class="type" value="range"> `;
                        break;
                    default:
                        alert(`No such question type`);
                }
                $(`.question-body`).last().html(layout);
            });
            
            function GenerateOptions(options, questionType){
                let questionCard = `<div class="options">`;
                
                options.forEach(answer => {
                    questionCard += `
                        <div class="options text-center">
                        <input type="text" value="${answer}" class="survey-field input_form answer-option mt-2 w-75" 
                            placeholder="Answer option">
                        </div>`
                });
                
                questionCard += `
                    <div id="controll" class="mt-3">
                        <input type="hidden" class="type" value="${type[questionType]}">
                        <input type="button" class="action-button survey-control survey-field mt-4 w-25"
                            id="add-option" value="Add options">
                    </div>
                `;
                
                return questionCard;
            }
        </script>
    </div>
    <div class="d-flex text-center">
          <input type="button" class="action-button survey-control survey-field m-3" id="add-question" value="Add Question"/>
          <button id="submit-survey" class="action-button survey-control survey-field m-3 btn-primary" type="button">Submit</button>
    </div>
</div>

@section Scripts
{
    <script src="~/js/AddOrEditSurvey.js"></script>
    <script>
            $(`#submit-survey`).on(`click`,
                async () => {
                    const surveyModel = {
                        id : '@Model.Id',
                        name: $(`#survey-name`).val(),
                        questions: $(`.question-card`).map(function () {
                            return {
                                title: $(this).find(`.question-title`).val(),
                                options: $(this).find(`.answer-option`).map(function (){
                                    return $(this).val();
                                }).get(),
                                type:questionType[$(this).find(`.type`).val()]
                            }
                        }).get()
                    };
                    
                    $.ajax({
                        type: "POST",
                        accept : "application/json",
                        contentType: "application/json",
                        url: `@Url.ActionLink("EditSurvey", "Surveys", new { id = string.Empty })`,
                        data: JSON.stringify(surveyModel),
                        success: function (response) {
                            alert(response.responseText);
                        },
                        failure: function (response) {
                            alert(response.responseText);
                        },
                        error: function (response) {
                            alert(response.responseText);
                       }
                    });
                }
            );
    </script>   
}